#!/usr/bin/with-contenv bash

s6-setuidgid www-data /etc/services.d/flexget/flexget-start.sh
#s6-setuidgid www-data /usr/bin/flexget -c /config/config.yml --loglevel debug daemon start --autoreload-config
#/usr/bin/flexget -c /config/config.yml --loglevel debug daemon start
