apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: gogs
  namespace: infra
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 3000
  - name: ssh  
    protocol: TCP
    port: 3022
  selector:
    app: gogs
status:
  loadBalancer: {}
