apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: registry
  namespace: infra
spec:
  type: LoadBalancer
  ports:
  - name: registry
    port: 5000
    protocol: TCP
  selector:
    app: registry
status:
  loadBalancer: {}
