apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wiki
  name: wiki
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wiki
    spec:
      containers:
      - env:
        - name: GID
          value: www-data
        - name: UID
          value: www-data
        - name: VIRTUAL_HOST
          value: wiki.duffyco.ca
        image: registry.duffyco.ca:5000/wiki:latest
        name: wiki
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /home
          name: wiki-home
        - mountPath: /etc/pki
          name: wiki-pki
      restartPolicy: Always
      volumes:
      - name: wiki-home
        hostPath:
           path: /mnt/services/wiki
           type: Directory
      - name: wiki-pki
        hostPath:
           path: /mnt/services/pki
           type: Directory
status: {}
