apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: wiki
  namespace: services
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: wiki
status:
  loadBalancer: {}
