apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-stack-services.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    app: www
  name: www
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: www
    spec:
      containers:
      - env:
        - name: VIRTUAL_HOST
          value: www.duffyco.ca
        image: registry.duffyco.ca:5000/www:latest
        name: www
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /home
          name: www-home
        - mountPath: /etc/nginx/sites-enabled
          name: www-config
        - mountPath: /etc/pki
          name: www-pki
      restartPolicy: Always
      volumes:
      - name: www-home
        hostPath:
           path: /mnt/services/www/data
           type: Directory
      - name: www-config
        hostPath:
           path: /mnt/services/www/sites-enabled
           type: Directory
      - name: www-pki
        hostPath:
           path: /mnt/services/pki
           type: Directory

status: {}
