apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: www
  namespace: services
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: www
status:
  loadBalancer: {}
