apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: roundcube
  namespace: mail
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: roundcube
status:
  loadBalancer: {}
